stages:
  - deploy

deploy:
  stage: deploy
  image: php:8.2-cli
  variables:
    FTP_SERVER: "72.62.213.250"
    FTP_USERNAME: "alenachgold"
    FTP_PASSWORD: 'aII-z;Z8Yp4SKv+xv1#F'
    FTP_PATH: "/home/achgoldestates-student-stay/htdocs/student-stay.achgoldestates.com/" 
  # before_script:
  #   - apt-get update && apt-get install -y lftp unzip git
  # script:
  #   - |
  #     lftp -u "$FTP_USERNAME","$FTP_PASSWORD" $FTP_SERVER <<EOF
  #     set ftp:ssl-allow no
  #     mirror -R --delete --verbose ./ $FTP_PATH
  #     quit
  #     EOF
  # only:
  #   - dev

  before_script:
    - apt-get update && apt-get install -y lftp unzip git
  script:
    - |
      lftp -u "$FTP_USERNAME","$FTP_PASSWORD" $FTP_SERVER <<EOF
      set ftp:ssl-allow no
      mirror -R --verbose --only-newer --exclude-glob vendor --exclude-glob .env ./ $FTP_PATH
      quit
      EOF
  only:
    - dev