stages:
  - deploy

deploy:
  stage: deploy
  image: php:8.2-cli
  variables:
    # New Server Details
    FTP_SERVER: "72.62.213.250"
    FTP_USERNAME: "backend_ftp"
    FTP_PASSWORD: "5wKYxieo6Sp5ZWic8oDs"
    # Keeping the path relative to the FTP root provided

    FTP_PATH: "/" 
  before_script:
    - apt-get update && apt-get install -y lftp unzip git
  script:
    - |
      lftp -u "$FTP_USERNAME","$FTP_PASSWORD" $FTP_SERVER <<EOF
      set ftp:ssl-allow no
      mirror -R --verbose --only-newer --exclude-glob vendor/ --exclude-glob .env --exclude-glob .git/ ./ $FTP_PATH
      quit
      EOF
  only:
    - dev